### ISSUE TITLE
Empty output when activated extension

### ISSUE THREAD

**Issue by tlygnersjo** [EdgarGomez/m2-CookieMsg#1]
Hi,

I've just tried this extension and it is being activated correct but the message/labels/links don't show up.

This is the output i get:
```
<div id="eg-cm-wrap" class="">
    <span>
        <a href="" id="eg-cm-ll"></a>
        <br>
    </span>
</div>
```

As you may see above, none of the information that i input in admin is shown. Also if i set the extension to "Developer mode" to "yes" the wrapper has "display: none". Is this a bug?

Could you please help me fix this issue?

I'm using Magento 2.1.2.

@EdgarGomez

**Comment by tlygnersjo** [comment]
When trying to debug your code it seems that the configuration seems to result in the value NULL for every variable (i.e. $lifeTime, $message).

I've also seen a misspelling in "/view/frontend/templates/cookiemsg.phtml", you should change $mesgPosition to $msgPosition.

**Comment by tlygnersjo** [comment]
Also I saw a few options in /Model/Source/CrossPosition.php for positioning the close cross, but thats not visible in admin. Is this a upcoming feature or a bug?

It would be great to position close cross.

**Comment by EdgarGomez** [comment]
Hi @tlygnersjo!

Thanks for your comments. You are right, there was an error in the cookie name. Now, the developer mode must work perfectly and the normal mode too. Just remember to clear the Magento cache every time you change anything in the content.

Also modified the  $msgPosition misspelling error.

About the crossPosition, yes, I want to make some improvements. Not only changing the position of the close cross directly in the configuration. I want to add some more extra configurations like different base templates/themes for the box. I guess this will be done and uploaded in one or two weeks.

Let me know if now is working for you.

Regards

**Comment by tlygnersjo** [comment]
Hi @EdgarGomez 

Thanks for your quick reply!

Great, yes i've uploaded the changes and cleared cache but output is still empty (see above output). Any other ideas why its not working? Could it be some namespace or function that is misspelled? Seems that everything from $helper->getConfig() is empty result except $helper->getConfig('edgargomez_cookiemsg/general/enable') which is 1 or true. But maybe thats because it has a default setting in a XML-config?

Sounds good with those options, looking forward to see those implemented.

<img width="1620" alt="magento2-configuration" src="https://cloud.githubusercontent.com/assets/5164069/23256061/33f2f0fc-f9be-11e6-98c9-b5adb884deb7.png">
<img width="647" alt="magento2-view-source" src="https://cloud.githubusercontent.com/assets/5164069/23256062/33f310c8-f9be-11e6-9095-a8e5b91f7ef5.png">

**Comment by EdgarGomez** [comment]
Hi @tlygnersjo 

Thats weird. I've just downloaded this extension again, installed it and it's working in my dev environment with the same data as in your image.

![ms2cookie](https://cloud.githubusercontent.com/assets/4573062/23275361/8a032082-fa06-11e6-80ea-4915e0ad6dca.png)

(The other information are "echo's" for each field)

I'm going to review it deeply. In the meanwhile try to give more feedback. For example, did you checked the logs? Is there any error? Did you checked the javascript console? Can you check the database and see if the data is being stored? I think is being stores because you can see the fields in the backoffice.

I will answer you with more information in a while.

Regards

**Comment by EdgarGomez** [comment]
Hello again @tlygnersjo 

I've uploaded new changes, fixing some misspelling errors (again) and adding the close cross position option. I've reviewed the code and it looks fine and works fine to me. Can you check in you terminal if you have the application in developer mode? Run the command "php bin/magento deploy:mode:show". This is just to understand if this can be the reason the module is not working for you.

I'll wait for your feedback.

Best

**Comment by tlygnersjo** [comment]
Hi,

Thank so much for your help!

I'll get back to you as soon as i have tried it.

I'm not using developer mode (its in production mode), but i've also run the following commands in order to compile/update the views/cache:
- php bin/magento setup:upgrade
- php bin/magento cache:clean
- php bin/magento setup:static-content:deploy

**Comment by tlygnersjo** [comment]
It seems to be stored in the DB:
![magento2-db](https://cloud.githubusercontent.com/assets/5164069/23280844/0f057096-fa1b-11e6-8d66-18c211042ae1.png)

**Comment by tlygnersjo** [comment]
Even if thats stored in the DB it isn't visible on frontend or in view source.

I've got one JS error in console but thats because your config isn't read for some reason.

All rows that sets a cookie lacks the parameter for "expires:" and think thats because config isn't read correctly.

`$.cookie('eg_cookiemsg', "true", { expires: , path: '/' });`

**Comment by tlygnersjo** [comment]
I've also flushed all caching and javascript/css cache

**Comment by tlygnersjo** [comment]
I tried adding this (/app/code/Edgargomez/CookieMsg/view/frontend/templates/cookiemsg.phtml) below declared variables:
```
    var_dump($lifeTime);
    var_dump($privacyUrl);
    var_dump($privacyLinkText);
    var_dump($privacyTitle);
    var_dump($message);
    var_dump($showAccept);
    var_dump($acceptText);
    var_dump($msgPosition);
    var_dump($showCross);
    var_dump($crossPosition);
    var_dump($devMode);
    var_dump($custom_css);
```

And it outputs this:
![magento2-output](https://cloud.githubusercontent.com/assets/5164069/23281124/4e862a0c-fa1c-11e6-9f09-0c6466b35bdc.png)

**Comment by tlygnersjo** [comment]
I hope that helps you to further debug the issue? @EdgarGomez

**Comment by tlygnersjo** [comment]
Any ideas what could be wrong? @EdgarGomez

**Comment by EdgarGomez** [comment]
Hi @tlygnersjo, can you try in a fresh installation of Magento 2, set the application in developer mode and test the module? I'm trying some fast testing in my dev project but it appear to be working every time I install the module.

**Comment by tlygnersjo** [comment]
Hello @EdgarGomez 

Thanks for your reply!

Yes I've tried that now and it works on a fresh installation. What could be causing it to not showing that information on the other installation?

As I'm close to a release of this ecommerce i can't start from scratch because of one extension i'm afraid. Any idea how we can debug/fix it?

**Comment by EdgarGomez** [comment]
Hello @tlygnersjo tested in another site and it works. I don't know what else can be. 

I think there is something in your ecommerce that can be crashing this module for some reason. Can be another module, a configuration or maybe other thing. Steps you can follow to try to solve this:

1. Disable all the extensions you added and clean cache, try it now.
2. Delete all the references from the database and from the code, make sure you install the module by pasting the folder "Edgargomez" into app/code/. Delete cache and try it.

If those steps are didn't work, I'm afraid I can look nothing else without looking directly into your project code.

Best

**Comment by tlygnersjo** [comment]
Hi again @EdgarGomez 

I'm not really sure what was causing the problem but now it works. I've compiled/cleared cache/static files serveral times but after a compile (setup:upgrade, cache:clean and deploy:static-content) today it solved itself.

Thank so much for a great extension and for all your help so far!

**Comment by EdgarGomez** [comment]
Niiiiiice. Good to hear that @tlygnersjo 

I hope you enjoy the extension.

Good luck with your project.
